### PR TITLE
Add gemfile to support local rendering

### PR DESCRIPTION
**Pull request by stijnvanhoey**
This PR adds the required `Gemfile` to enable local serving of the website, instead of only the session presentations. 

I tested this (on linux) with jekyll 4, `jekyll-theme-minimal` installed and [these](https://github.com/pages-themes/minimal#previewing-the-theme-locally) instructions. 

I had to use the `serve` command in combination with `bundle exec`. After adding the Gemfile, rendering locally can be done from the docs folder with the command: 

```
bundle exec jekyll serve --baseurl ""
```

__Note:__ I do think you can ignore the warning `Invalid theme folder: _includes` when building.

### CODE REVIEW

**Comment by niconoe** [comment]
Looks great to me!

**Comment by damianooldoni** [comment]
Thanks @stijnvanhoey! I give a look right now.

**Comment by damianooldoni** [comment]
Thanks! I get it on Windows as well. :+1: 
I got first some errors, after running `bundle install` (https://github.com/rubygems/bundler/issues/2780#issuecomment-31283368) it worked all fine.

**Comment by damianooldoni** [comment]
@stijnvanhoey : as founder of the INBO coding club and developer of its website, I think you should have the honor of merging this PR to the master!

**Pull request merged**
