### PR TITLE
Reorganized tree structure by session date

### PR DESCRIPTION
**Pull request by niconoe**
I restructured the `/data` and `/src` according to what was discussed in #14. Not there are a few remaining files in `/data` with no date prefix. Should we investigate those to see if they are linked to a specific session or not?

### CODE REVIEW

**Comment by damianooldoni** [comment]
Thanks @niconoe. They are old files linked to very first sessions. I will give a look. But it is not a big issue. Slides are also pdfs with broken links to Google drive files...

**Comment by damianooldoni** [comment]
Actually, I forgot I already put a date to them! 
I see relative recent files, so errors in filenaming. Good you let us know.
I add date in their name in `master`. Then you can pull my changes in your branch and finalizze the PR, ok?

**Comment by niconoe** [comment]
Sure, sounds good!

**Comment by damianooldoni** [comment]
Not easy to find how these files are there, but I recap the situation and how I tackled them:

file | description | action
--- | ---
grofwild.csv | Add by Sander as challenge 4: bonus challenge was not enough :smile: | renamed to 20190423_grofwild.csv
0000962-190415153152247.csv | Added in first draft of TDWG workshop in Leiden, but not used anymore in final version | deleted
coding_club_pipe_example.csv | Added in first draft of TDWG workshop in Leiden, but not used anymore in final version | deleted
oppervlakte_straat_wijken_Brugge | Used in coding club session of 18-09-2019 | renamed: 20190918_oppervlakte_straat_wijken_Brugge and link updated in slides and solutions
20190918_oppervlakte_straat_wijken_Antwerpen.csv | Used in coding club session of 24-09-2019 | renamed: 20190918_oppervlakte_straat_wijken_Antwerpen.csv and link updated in slides, challenge R script and solutions

**Comment by damianooldoni** [comment]
@niconoe : done. The conflicts are just a rename of two files in the code (I have added `20190924_`). So, I hope you can easily solve them. Just let me know if you need help about it. Thanks a lot.

**Comment by damianooldoni** [comment]
Hi @niconoe. This morning I was thinking it would be better to update via this PR all links in all `.html` files in `docs/sessions/` so that all links continue to work. Actually it goes about replacing all 8 digits followed by `_` with the same 8 digits + `/` + same 8 digits + `_`. The pattern to be found via regex is `\d{8}_{1}`. The major issue is using the very same regex in the replacement as well.
With Python I think the solution is working with a dictionary `{[pattern1] : replacement1, ...}`.

In R we do it using str_replace_all() with the replacements as a named vector using the patterns as names. Here below a reproducible example on a vector of strings.

```r
> library(purrr)
> library(stringr)
> texts <- c(
+   "test ./data/20190423_filename.csv/nabc src/20200104_challlenges.R\nqsdqsdqsdqsdqsd /src/20190423_challenges_solutions.R",
+   "qsdqsd ./data/20200108_filename.csv/n{test}test2 ./github/blob/master/data/20200108_challenge1.R/n<end>"
+ )
> texts
[1] "test ./data/20190423_filename.csv/nabc src/20200104_challlenges.R\nqsdqsdqsdqsdqsd /src/20190423_challenges_solutions.R"
[2] "qsdqsd ./data/20200108_filename.csv/n{test}test2 ./github/blob/master/data/20200108_challenge1.R/n<end>"                
> to_be_replaced <- str_extract_all(string = texts, pattern = "\\d{8}_{1}")
> to_be_replaced <- map(to_be_replaced, ~unique(.))
> replacements <- map(to_be_replaced, function(x) {
+   map_chr(x, function(y) {
+     paste0(substr(y, 1, 8), "/", y)
+   })
+ })
> replacements <- map(replacements, ~(unique(.)))
> improved_texts <- pmap(list(texts, to_be_replaced, replacements),
+      function(s, x, y) {
+        names(y) <- x
+        str_replace_all(string = s, y)
+      })
> improved_texts
[[1]]
[1] "test ./data/20190423/20190423_filename.csv/nabc src/20200104/20200104_challlenges.R\nqsdqsdqsdqsdqsd /src/20190423/20190423_challenges_solutions.R"

[[2]]
[1] "qsdqsd ./data/20200108/20200108_filename.csv/n{test}test2 ./github/blob/master/data/20200108/20200108_challenge1.R/n<end>"
```

I don't say this is the fastest way to do it in R, but I didn't find better. Still, I am quite sure that it will be easier with Python by using dictionaries.

**Comment by hansvancalster** [comment]
@damianooldoni there is a simpler way to do this in R using capturing groups in the regexp. Continuing your example:

`````
improved_texts2 <- str_replace_all(string = texts, 
                                  pattern = "((\\d{8})_{1})", 
                                  replacement = "\\2/\\1")
all.equal(unlist(improved_texts), improved_texts2)  
`````

**Comment by damianooldoni** [comment]
Thanks @hansvancalster. Even today I've learned something :partying_face:

**Comment by niconoe** [comment]
Thanks @hansvancalster and @damianooldoni!

I just merged your changes into this PR. If I'm not mistaken, it should now be complete and mergeable!

**Comment by damianooldoni** [comment]
Hi @niconoe! I didn't rename the links in html files in master. But I can do it easily on master based on @hansvancalster solution if you have no time to do it now.

**Comment by niconoe** [comment]
No worries Damiano I'll take care of it, I just misunderstood that it was already done!

**Comment by damianooldoni** [comment]
Ok. Then I wait to merge it. As you prefer.

**Comment by niconoe** [comment]
I'm working on it, but the regular expression also match (and changes!) other resources (cheat sheets and images, in `docs/assets`. So we'll have to be careful, and maybe also restructurethose directories.

**Comment by damianooldoni** [comment]
Actually yes, we should restructure `docs/assets` as well. About the cheat sheets, they are very few and I would not divide them in subdirectories. The date is only used to trace changes in cheat sheets as they also can change over time (e.g. dplyr's cheat sheet). Maybe you can avoid to change them by regex again checking whether `cheat_sheets/` precedes the digits?

**Comment by niconoe** [comment]
I *think* the structure and links are now ok!

**Comment by hansvancalster** [comment]
Looks good! I noticed two csv files in the `data` folder that were not assigned to a `data/yyyymmdd` folder. 
Also the `readme.md` file will need updating (section about repo structure).
We should probably also check locally if the website will build as expected? Not sure how to do that, but I guess a function in `pckgdown` is needed to test this?

**Comment by damianooldoni** [comment]
Yes, you are right, @hansvancalster.
About building the website, @niconoe and I are trying to understand how to build it locally with jekyll. More or less we got it, but we have just sent an email to Stijn for know some more about it and so improving the documentation in [workflow page](https://inbo.github.io/coding-club/workflow.html).

**Comment by niconoe** [comment]
Thanks @hansvancalster! I just fixed those two issues.

I also realised there's one more thing to update: the path to data files in the exercises (code in `/src`) :)

**Comment by niconoe** [comment]
I think the structure and links are now ok! 😁😁

**Pull request merged**
